A few things
graysky2/kodi-standalone-service pull request #38
Opened 2022-01-17 10:18 UTC by solsticedhiver

Tell me what you think about this.

This goes from fixing typo, to check the architecture in the Makefile, install polkit.rules, and the last ...

I don't know yet. Is the patch really needed ? Waiting comment in raspberrypi os forum, if any comes https://forums.raspberrypi.com/viewtopic.php?p=1960785&hilit=kodi+systemd#p1960785

2022-01-17 11:25 UTC, graysky2 submitted a review, later dismissed

2022-01-17 11:32 UTC, graysky2 commented
Looks decent.  Let's see what the RPiOS folks say. @popcornmix - can you comment on the modification made?  See the forum post above and https://github.com/graysky2/kodi-standalone-service/issues/37

2022-01-17 12:13 UTC, graysky2 requested changes

2022-01-17 12:13 UTC, graysky2 commented on Makefile
> +ifneq ($(cat /proc/cpuinfo | grep -q ARM),"")
I am unfamiliar with using an error code like this, but in testing, this check always selects x86 even on an ARM device.

An aside: `grep -q ARM /pro/cpuinfo` would be better.

2022-01-17 12:45 UTC, graysky2 requested changes
Still not working

2022-01-17 12:45 UTC, graysky2 commented on Makefile
> +ifeq ($(IS_ARCH_ARM), 0)
I still this this is not working.  The variable IS_ARCH_ARM does not get assigned 0 or 1 it seems to be a null so the check always ends up as x86.

2022-01-17 12:54 UTC, graysky2 commented on Makefile
> +	$(INSTALL_DIR) "$(DESTDIR)$(POLKDIR)"
The polkit dir and file is only needed for arm not x86_64.  Please move these two lines under that conditional.

2022-01-17 12:57 UTC, graysky2 requested changes
polkit dir and file only needed for ARM, please move

2022-01-17 12:57 UTC, graysky2 commented on Makefile
> +	$(INSTALL_DIR) "$(DESTDIR)$(POLKDIR)"
This is only needed for ARM; please move under line 37

2022-01-17 12:57 UTC, graysky2 commented on Makefile
> +	$(INSTALL_DATA) $(ARCH)/polkit/polkit.rules "$(DESTDIR)$(POLKDIR)/99-kodi.rules"
This is only needed for ARM; please move under line 37

2022-01-17 13:08 UTC, graysky2 commented
I corrected it on the shell.  Not very adept with github's interface.  Let's wait to see about updating the README based on comment.  Closing this since I cherry-picked the changes.  Thank you for contributing!

2022-01-17 13:08 UTC, closed without merging

2022-01-17 16:20 UTC, solsticedhiver commented
No problem. I saw the problem about polkit dir and arm,a nd push and squash a new commit. 
Before I had to go. sorry.

And that's weird, it was working for me without the "shell" keyword. (But yes, I wrongly copied that without the correct shell keyword /o\)
Never mind.

2022-01-17 16:34 UTC, graysky2 commented
It's working fine now in my testing.  Good improvement.

2022-01-26 17:27 UTC, ghen2 commented
> polkit dir and file only needed for ARM, please move

Does this mean the x86_64 package can drop the polkit dependency ?
(kodi-standalone-service is the only dependent on polkit on my Arch HTPC)

2022-01-26 17:36 UTC, ghen2 commented
Yes, it seems needed for the poweroff/reboot capabilities (even without the polkit rules file).